feat: adding alert css and documentation page
ultronjs/Dash-CSS pull request #4
Opened 2022-01-31 17:24 UTC by ultronjs

2022-01-31 18:18 UTC, t007rushi requested changes
Just one more thing site looks good just use a different extension for code snippet just suggestion

2022-01-31 18:18 UTC, t007rushi commented on .vscode/settings.json
> +{
you can remove/untrack or can use .gitignore as no need of this file in remote repo

2022-01-31 18:18 UTC, t007rushi commented on css/abstracts/_variables.css
> +    /* --secondary_background: #897cb4; */
I think you can reconsider naming & comments for easy in reading & future use

2022-02-01 01:55 UTC, Raghav888 approved these changes
Looks good

2022-02-01 06:13 UTC, merged